<?php
/**
 * Test class for Lock.
 * Generated by PHPUnit on 2011-03-25 at 22:46:43.
 */
namespace RedisTools;

class LockTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Lock
	 */
	protected $object;

	protected $testKey = 'testkey';
	
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$redis = new \Redis();
		$redis->pconnect('127.0.0.1');
		
		$this->object = new Lock(
			$this->testKey, $redis
		);
		
		$this->object->delete();
	}
	
	public function testGetLock()
	{
		$this->assertTrue(
			$this->object->getLock()
		);
		
		$this->assertFalse(
			$this->object->getLock()
		);
	}

	public function testReleaseLock()
	{
		$this->assertTrue(
			$this->object->releaseLock()
		);
		
		$this->assertTrue(
			$this->object->getLock()
		);
		
		$this->assertTrue(
			$this->object->releaseLock()
		);
		
		$this->assertTrue(
			$this->object->getLock()
		);
		
	}
	
}

?>
