<?php
/**
 * Test class for RedisTools\Manager.
 * Generated by PHPUnit on 2011-03-23 at 21:23:45.
 */
namespace RedisTools;

class ManagerTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Manager
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Manager();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}
	
	public function testConstruct()
	{
		
	}

}

?>
