<?php
namespace RedisTools\Db\Field;

/**
 * Test class for UniqueIdentifier.
 * Generated by PHPUnit on 2011-06-27 at 22:51:49.
 */
class UniqueIdentifierTest extends TestBase
{
	/**
	 * @var UniqueIdentifier
	 */
	protected $object;

	protected $lookupTableKey;

	protected function setUp()
	{
		$this->object = new UniqueIdentifier($this->getValueObject());
		$this->object->setName('test');
		$this->lookupTableKey = md5($this->getValueObject()->getKey() . $this->object->getName());
	}

	public function tearDown()
	{
		$this->getRedis()->delete($this->lookupTableKey);
		parent::tearDown();
	}

	public function testHasObjectValue()
	{
		$this->assertTrue($this->object->hasObjectValue());
	}

	/**
	 * @expectedException \RedisTools\Exception
	 */
	public function testGetLookupTableWithInvalidKey()
	{
		$object = new UniqueIdentifier($this->getValueObject());
		$table = $object->getLookupTable();
	}

	public function testGetLookupTable()
	{
		$this->object->setValue('asdf');
		$expected = $this->lookupTableKey;
		$table = $this->object->getLookupTable();
		$this->assertInstanceOf('RedisTools\Type\Hash', $table);
		$this->assertEquals($expected, $table->getKey());
	}

	public function testOnSaveWithoutValue()
	{
		$this->assertFalse( $this->object->onSave() );
	}

	public function testOnSave()
	{
		$this->object->setValue('asdf');
		$this->assertTrue( $this->object->onSave() );
		$this->assertEquals($this->getValueObject()->getKey(), $this->object->getLookupTable()->getValue('asdf'));
	}

}
?>
