<?php

/**
 * Test class for RedisTools.
 * Generated by PHPUnit on 2011-04-05 at 00:54:56.
 */
class RedisToolsTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var RedisTools
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new RedisTools;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	public function testSetRedis()
	{
		RedisTools::setRedis(new Redis());
	}

}

?>
