<?php

namespace PRTools;

/**
 * Test class for Key.
 * Generated by PHPUnit on 2011-03-24 at 23:33:38.
 */
class KeyTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Key
	 */
	protected $object;

	protected $testKey = 'testkey';

	protected $testValue = 'testvalue';


	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$redis = new \Redis();
		$redis->pconnect('127.0.0.1');
		
		$this->object = new Key(
			$this->testKey, $redis
		);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		$this->object->delete();
		$this->object = null;
	}
	
	public function testSettingValue()
	{
		$this->assertTrue(
			$this->object->set( $this->testValue ),
			'Value could not be written to Redis. '
		);
	}
	
	public function testSettingValueWithRedisError()
	{
		$redis = $this->getMock('Redis', array('set'));
		$key = new Key('asdf', $redis);
		$key->set('value');
		
	}
	
	public function testReadingValue()
	{
		$this->assertFalse(
			$this->object->get(), 
			'Key should have been empty but was not. '
		);
		
		$this->object->set($this->testValue);
		
		$this->assertEquals(
			$this->testValue, 
			$this->object->get(),
			'Wrong value read from a Redis key. '
		);
	}
	
	public function testDeletingValue()
	{
		$this->object->set($this->testValue);
		
		$this->assertEquals(
			1, $this->object->delete(), 
			'Value should have been deleted but was not. '
		);
		
		$this->assertEquals(
			0, $this->object->delete(), 
			'Value should have already been deleted but was present. '
		);
	}
	
	
}

?>
