<?php

namespace RedisTools\Type;
/**
 * Test class for Bitmap.
 * Generated by PHPUnit on 2011-03-28 at 23:51:37.
 */
class BitmapTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Bitmap
	 */
	protected $object;

	protected $testKey = 'key';


	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$redis = new \Redis();
		$redis->pconnect('127.0.0.1');
		
		$this->object = new Bitmap( $this->testKey );
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		$this->object->delete();
	}

	/**
	 * @todo Implement testSetBit().
	 */
	public function testSetBit()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetBit().
	 */
	public function testGetBit()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}

?>
