<?php

namespace RedisTools\Type;
/**
 * Test class for Bitmap.
 * Generated by PHPUnit on 2011-03-28 at 23:51:37.
 */
class BitmapTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Bitmap
	 */
	protected $object;

	protected $testKey = 'key';


	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$redis = new \Redis();
		$redis->pconnect('127.0.0.1');
		
		$this->object = new Bitmap( $this->testKey, $redis );
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		$this->object->delete();
	}

	public function testSetBitToFirstPosition()
	{
		$this->assertEquals(0,
			$this->object->setBit( 0, 1 )
		);
		
		$this->assertEquals(1,
			$this->object->setBit( 0, 1 )
		);
		
		$this->assertEquals(1,
			$this->object->setBit( 0, 0 )
		);
		
		$this->assertEquals(1, 
			$this->object->getRedis()->strlen($this->testKey)
		);
	}
	
	public function testSetBitToOtherPosition()
	{
		$this->assertEquals(0,
			$this->object->setBit( 9, 1 )
		);
		
		$this->assertEquals(2, 
			$this->object->getRedis()->strlen($this->testKey),
			'Every 8 bits one byte should be added. So 9 bits should be 2 chars. '
		);
	}

	public function testGetBit()
	{
		$this->object->setBit( 5, 1);
		$this->object->setBit( 2, 1);
		$this->object->setBit( 10, 1);
		$this->object->setBit( 445, 1);
		
		$this->assertEquals(1, $this->object->getBit(5));
		$this->assertEquals(1, $this->object->getBit(2));
		$this->assertEquals(1, $this->object->getBit(10));
		$this->assertEquals(1, $this->object->getBit(445));
		
		$this->assertEquals(0, $this->object->getBit(1));
		$this->assertEquals(0, $this->object->getBit(100));
		$this->assertEquals(0, $this->object->getBit(11));
		$this->assertEquals(0, $this->object->getBit(5268));
	}

}

?>
