<?php

namespace RedisTools\Type;

/**
 * Test class for Key.
 * Generated by PHPUnit on 2011-03-24 at 23:33:38.
 */
class StringTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var String
	 */
	protected $object;

	protected $testKey = 'testkey';

	protected $testValue = 'testvalue';

	protected $testTtl = 2;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$redis = new \Redis();
		$redis->pconnect('127.0.0.1');
		
		$this->object = new String(
			$this->testKey, $redis
		);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		$this->object->delete();
		$this->object = null;
	}
	
	public function testSettingValue()
	{
		$this->assertTrue(
			$this->object->setValue( $this->testValue ),
			'Value could not be written to Redis. '
		);
	}
	
	public function testGetSettingValueOnEmptyString()
	{
		$this->assertFalse(
			$this->object->getSetValue( 'asdf' )
		);
		$this->assertEquals('asdf',
			$this->object->getValue()
		);
	}

	public function testGetSettingValue()
	{
		$this->object->setValue('old');
		$this->assertEquals('old',
			$this->object->getSetValue( 'new' )
		);
		$this->assertEquals('new',
			$this->object->getValue()
		);
	}

	public function testSetValueWithExpires()
	{
		$this->assertTrue(
			$this->object->setValue( 
				$this->testValue,
				$this->testTtl
			),
			'Value with expires time could not be written to Redis. '
		);
		
		$ttl = $this->object->getTtl();
		$this->assertEquals(
			$this->testTtl, $ttl,
			'TTl should be '. $this->testTtl . ' but was ' . $ttl . '. '
		);
	}
	
	public function testSetNonExistingString()
	{
		$this->assertTrue(
			$this->object->setValueIfNotExists( $this->testValue ),
			'Setting value on empty key was not successful. '
		);
		
		$this->assertEquals(
			$this->testValue, 
			$this->object->getValue(),
			'Value should have been set but was not. '
		);
	}

	public function testSetIfNotExistsWithExistingValue()
	{
		$this->object->setValue($this->testValue);
		
		$this->assertFalse(
			$this->object->setValueIfNotExists( 'some other' ),
			'Setting value should not be successful but was. '
		);
		
		$this->assertEquals(
			$this->testValue, 
			$this->object->getValue(),
			'Value has been changed but should not. '
		);
	}

	public function testSettingValueWithRedisError()
	{
		$redis = $this->getMock('Redis', array('setValue'));
		$key = new String('asdf', $redis);
		$key->setValue('value');
		
	}
	
	public function testReadingValue()
	{
		$this->assertFalse(
			$this->object->getValue(), 
			'Key should have been empty but was not. '
		);
		
		$this->object->setValue($this->testValue);
		
		$this->assertEquals(
			$this->testValue, 
			$this->object->getValue(),
			'Wrong value read from a Redis key. '
		);
	}
	
	public function testGetLengthOnEmptyString()
	{
		$this->assertEquals(0,
			$this->object->getByteLength()
		);
	}
	
	public function testGetLengthOnWrongRedisType()
	{
		$this->object->getRedis()->hSet($this->testKey, 'asdf', 'asdf');
		$this->assertFalse(
			$this->object->getByteLength()
		);
	}
	
	public function testGetLengthOnInteger()
	{
		$this->object->setValue(4);
		$this->assertEquals(1,
			$this->object->getByteLength()
		);
	}
	
	public function testGetLengthOnString()
	{
		$this->object->setValue('asdf');
		$this->assertEquals(4,
			$this->object->getByteLength()
		);
	}
	
	public function testGetLengthOnStringWithSpecialChars()
	{
		$this->object->setValue('öäüà');
		$this->assertEquals(8,
			$this->object->getByteLength()
		);
	}
}