<?php
namespace RedisTools\Utils;
/**
 * Test class for String.
 * Generated by PHPUnit on 2011-04-21 at 20:45:18.
 */
class StringTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var String
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new StringOperations();
	}

	public function testSplitCamelCase()
	{
		$string = "getNameByValueOrderbyOrdervalueDesc";
		$result = $this->object->splitCamelCase($string);
		$this->assertType('array', $result);
		
		$this->assertEquals('get', $result[0]);
		$this->assertEquals('By', $result[2]);
		$this->assertEquals('Ordervalue', $result[5]);
	}

}

?>
