<?php
/**
 * Test class for Uid.
 * Generated by PHPUnit on 2011-03-23 at 23:32:24.
 */
namespace RedisTools\Utils;

class UidTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Uid
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new Uid();
	}

	protected function tearDown()
	{
		$this->object = null;
	}
	
	public function testConstruct()
	{
		$this->assertType('\RedisTools\Utils\Uid', $this->object);
	}
	
	public function testGenerate()
	{
		$this->assertType('string', $this->object->generate());
		$this->assertEquals(32, strlen($this->object->generate()));
		
		$this->assertType('string', $this->object->generate('some seed value'));
		$this->assertEquals(32, strlen($this->object->generate('some other seed value')));
		
	}
	
	public function testGenerateMultipleIds()
	{
		$ids = array();
		for($i=0; $i<10; $i++)
		{
			$ids[]= $this->object->generate();
		}

		foreach($ids as $key => $id)
		{
			foreach($ids as $key2 => $id2)
			{
				if($key != $key2)
				{
					$this->assertNotEquals($id, $id2);
				}
			}
		}
	}

}

?>
